AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Battlesnake serverless snake
Resources:
  Function:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.handler
      Runtime: python3.9
      CodeUri: .
      Description: Battlesnake serverless snake
      MemorySize: 512
      Timeout: 10
      Policies: []
      Events:
        Api:
          Type: Api
          Properties:
            Path: '/{proxy+}'
            Method: ANY
  Function2:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.info
      Runtime: python3.9
      CodeUri: .
      Description: Battlesnake serverless snake info
      MemorySize: 512
      Timeout: 10
      Policies: [ ]
      Events:
        Api:
          Type: Api
          Properties:
            Path: '/'
            Method: GET
